require: rubocop-sketchup
inherit_from: https://raw.githubusercontent.com/SketchUp/rubocop-sketchup/master/sketchup-style.yml

AllCops:
  # This prevents normal RuboCop cops to run. Disable this to get full static
  # analysis of your Ruby code.
  DisabledByDefault: true
  NewCops: disable

  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
  - src/*/vendor/**/* # Exclude skippy vendor folder
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2021
    Exclude: # Exclude common folders.
    - profiling/
    - skippy/
    - tests/
  TargetRubyVersion: 2.7.1 # Should have been 2.0 but RuboCop dropped support.

# If DisabledByDefault is set to true then we need to enable the SketchUp
# related departments:
SketchupDeprecations:
  Enabled: true

SketchupPerformance:
  Enabled: true

SketchupRequirements:
  Enabled: true

SketchupSuggestions:
  Enabled: true

SketchupBugs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout:
  EmptyLineBetweenDefs:
    NumberOfEmptyLines: 1
    AllowAdjacentOneLineDefs: false
  EmptyLineBetweenMethodDefs/Enabled: true
  EmptyLineBetweenClassDefs/Enabled: true
  EmptyLineBetweenModuleDefs/Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
