include:
- "src/**/*.rb"
require:
- "sketchup-api-stubs"
domains: []
reporters:
- rubocop
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths:
- "src"
- "../../../../../Program Files/SketchUp/SketchUp 2021/Tools/"
plugins: []
max_files: 5000
